-- this file is machine generated.  do not edit.

local AL = LibStub:GetLibrary("AchievementLocations-1.0")
local function A(row) AL:AddLocation(row) end

-- World Events/Brewfest: Direbrewfest
A{"BlackrockDepths", 295, 0.4660, 0.6000, floor=2, season="Brewfest", trivia={module="seasonal_brew", category="World Events/Brewfest", name="Direbrewfest", description="Kill Coren Direbrew.", points="10", parent="World Events"}}

-- World Events/Brewfest: Disturbing the Peace
A{"Dalaran", 293, season="Brewfest", trivia={module="seasonal_brew", category="World Events/Brewfest", name="Disturbing the Peace", description="While wearing 3 pieces of Brewfest clothing, get completely smashed and dance in Dalaran.", points="10", parent="World Events"}}

-- World Events/Brewfest: Strange Brew
A{"DunMorogh", 1184, 0.4950, 0.3880, criterion=8879, side="alliance", season="Brewfest", trivia={criteria="Thunder 45", module="seasonal_brew", category="World Events/Brewfest", name="Strange Brew", description="Acquire the Brewfest beers listed below. Don't drink them all at once!", points="10", parent="World Events", type="36"}}
A{"DunMorogh", 1184, 0.4890, 0.3980, criterion=8883, side="alliance", season="Brewfest", trivia={criteria="Barleybrew Light", module="seasonal_brew", category="World Events/Brewfest", name="Strange Brew", description="Acquire the Brewfest beers listed below. Don't drink them all at once!", points="10", parent="World Events", type="36"}}
A{"DunMorogh", 1184, 0.4840, 0.3840, criterion=8878, side="alliance", season="Brewfest", trivia={criteria="Gordok Grog", module="seasonal_brew", category="World Events/Brewfest", name="Strange Brew", description="Acquire the Brewfest beers listed below. Don't drink them all at once!", points="10", parent="World Events", type="36"}}
A{"DunMorogh", 1184, 0.4840, 0.3840, criterion=9014, side="alliance", season="Brewfest", trivia={criteria="Mudder's Milk", module="seasonal_brew", category="World Events/Brewfest", name="Strange Brew", description="Acquire the Brewfest beers listed below. Don't drink them all at once!", points="10", parent="World Events", type="36"}}
A{"DunMorogh", 1184, 0.4840, 0.3840, criterion=8882, side="alliance", season="Brewfest", trivia={criteria="Ogre Mead", module="seasonal_brew", category="World Events/Brewfest", name="Strange Brew", description="Acquire the Brewfest beers listed below. Don't drink them all at once!", points="10", parent="World Events", type="36"}}
A{"DunMorogh", 1184, 0.4950, 0.3880, criterion=8880, side="alliance", season="Brewfest", trivia={criteria="Thunderbrew Ale", module="seasonal_brew", category="World Events/Brewfest", name="Strange Brew", description="Acquire the Brewfest beers listed below. Don't drink them all at once!", points="10", parent="World Events", type="36"}}
A{"DunMorogh", 1184, 0.4950, 0.3880, criterion=8881, side="alliance", season="Brewfest", trivia={criteria="Thunderbrew Stout", module="seasonal_brew", category="World Events/Brewfest", name="Strange Brew", description="Acquire the Brewfest beers listed below. Don't drink them all at once!", points="10", parent="World Events", type="36"}}
A{"DunMorogh", 1184, 0.4890, 0.3980, criterion=8885, side="alliance", season="Brewfest", trivia={criteria="Barleybrew Clear", module="seasonal_brew", category="World Events/Brewfest", name="Strange Brew", description="Acquire the Brewfest beers listed below. Don't drink them all at once!", points="10", parent="World Events", type="36"}}
A{"DunMorogh", 1184, 0.4890, 0.3980, criterion=8884, side="alliance", season="Brewfest", trivia={criteria="Barleybrew Dark", module="seasonal_brew", category="World Events/Brewfest", name="Strange Brew", description="Acquire the Brewfest beers listed below. Don't drink them all at once!", points="10", parent="World Events", type="36"}}

-- World Events/Brewfest: The Brewfest Diet
A{"DunMorogh", 1185, 0.4890, 0.3830, criterion=18620, side="alliance", season="Brewfest", trivia={criteria="Succulent Sausage", module="seasonal_brew", category="World Events/Brewfest", name="The Brewfest Diet", description="Eat 8 of the Brewfest foods listed below.", points="10", parent="World Events", type="41"}}
A{"DunMorogh", 1185, 0.4890, 0.3830, criterion=18619, side="alliance", season="Brewfest", trivia={criteria="Dried Sausage", module="seasonal_brew", category="World Events/Brewfest", name="The Brewfest Diet", description="Eat 8 of the Brewfest foods listed below.", points="10", parent="World Events", type="41"}}
A{"DunMorogh", 1185, 0.4890, 0.3830, criterion=18622, side="alliance", season="Brewfest", trivia={criteria="Pickled Sausage", module="seasonal_brew", category="World Events/Brewfest", name="The Brewfest Diet", description="Eat 8 of the Brewfest foods listed below.", points="10", parent="World Events", type="41"}}
A{"DunMorogh", 1185, 0.4890, 0.3830, criterion=3544, side="alliance", season="Brewfest", trivia={criteria="Savory Sausage", module="seasonal_brew", category="World Events/Brewfest", name="The Brewfest Diet", description="Eat 8 of the Brewfest foods listed below.", points="10", parent="World Events", type="41"}}
A{"DunMorogh", 1185, 0.4930, 0.3940, criterion=18621, side="alliance", season="Brewfest", trivia={criteria="Spiced Onion Cheese", module="seasonal_brew", category="World Events/Brewfest", name="The Brewfest Diet", description="Eat 8 of the Brewfest foods listed below.", points="10", parent="World Events", type="41"}}
A{"DunMorogh", 1185, 0.4890, 0.3830, criterion=18623, side="alliance", season="Brewfest", trivia={criteria="Spicy Smoked Sausage", module="seasonal_brew", category="World Events/Brewfest", name="The Brewfest Diet", description="Eat 8 of the Brewfest foods listed below.", points="10", parent="World Events", type="41"}}
A{"DunMorogh", 1185, 0.4840, 0.3990, criterion=7987, side="alliance", season="Brewfest", trivia={criteria="The Essential Brewfest Pretzel", module="seasonal_brew", category="World Events/Brewfest", name="The Brewfest Diet", description="Eat 8 of the Brewfest foods listed below.", points="10", parent="World Events", type="41"}}
A{"DunMorogh", 1185, 0.4890, 0.3830, criterion=18624, side="alliance", season="Brewfest", trivia={criteria="The Golden Link", module="seasonal_brew", category="World Events/Brewfest", name="The Brewfest Diet", description="Eat 8 of the Brewfest foods listed below.", points="10", parent="World Events", type="41"}}
A{"Durotar", 1185, 0.4440, 0.1670, criterion=18620, side="horde", season="Brewfest", trivia={criteria="Succulent Sausage", module="seasonal_brew", category="World Events/Brewfest", name="The Brewfest Diet", description="Eat 8 of the Brewfest foods listed below.", points="10", parent="World Events", type="41"}}
A{"Durotar", 1185, 0.4440, 0.1670, criterion=18619, side="horde", season="Brewfest", trivia={criteria="Dried Sausage", module="seasonal_brew", category="World Events/Brewfest", name="The Brewfest Diet", description="Eat 8 of the Brewfest foods listed below.", points="10", parent="World Events", type="41"}}
A{"Durotar", 1185, 0.4440, 0.1670, criterion=18622, side="horde", season="Brewfest", trivia={criteria="Pickled Sausage", module="seasonal_brew", category="World Events/Brewfest", name="The Brewfest Diet", description="Eat 8 of the Brewfest foods listed below.", points="10", parent="World Events", type="41"}}
A{"Durotar", 1185, 0.4440, 0.1670, criterion=3544, side="horde", season="Brewfest", trivia={criteria="Savory Sausage", module="seasonal_brew", category="World Events/Brewfest", name="The Brewfest Diet", description="Eat 8 of the Brewfest foods listed below.", points="10", parent="World Events", type="41"}}
A{"Durotar", 1185, 0.4390, 0.1790, criterion=18621, side="horde", season="Brewfest", trivia={criteria="Spiced Onion Cheese", module="seasonal_brew", category="World Events/Brewfest", name="The Brewfest Diet", description="Eat 8 of the Brewfest foods listed below.", points="10", parent="World Events", type="41"}}
A{"Durotar", 1185, 0.4440, 0.1670, criterion=18623, side="horde", season="Brewfest", trivia={criteria="Spicy Smoked Sausage", module="seasonal_brew", category="World Events/Brewfest", name="The Brewfest Diet", description="Eat 8 of the Brewfest foods listed below.", points="10", parent="World Events", type="41"}}
A{"Durotar", 1185, 0.3370, 0.1740, criterion=7987, side="horde", season="Brewfest", trivia={criteria="The Essential Brewfest Pretzel", module="seasonal_brew", category="World Events/Brewfest", name="The Brewfest Diet", description="Eat 8 of the Brewfest foods listed below.", points="10", parent="World Events", type="41"}}
A{"Durotar", 1185, 0.4440, 0.1670, criterion=18624, side="horde", season="Brewfest", trivia={criteria="The Golden Link", module="seasonal_brew", category="World Events/Brewfest", name="The Brewfest Diet", description="Eat 8 of the Brewfest foods listed below.", points="10", parent="World Events", type="41"}}

-- World Events/Brewfest: Strange Brew
A{"Durotar", 1203, 0.4020, 0.1700, criterion=8889, side="horde", season="Brewfest", trivia={criteria="Brewdoo Magic", module="seasonal_brew", category="World Events/Brewfest", name="Strange Brew", description="Acquire the Brewfest beers listed below. Don't drink them all at once!", points="10", parent="World Events", type="36"}}
A{"Durotar", 1203, 0.4080, 0.1700, criterion=8878, side="horde", season="Brewfest", trivia={criteria="Gordok Grog", module="seasonal_brew", category="World Events/Brewfest", name="Strange Brew", description="Acquire the Brewfest beers listed below. Don't drink them all at once!", points="10", parent="World Events", type="36"}}
A{"Durotar", 1203, 0.4020, 0.1700, criterion=8888, side="horde", season="Brewfest", trivia={criteria="Jungle River Water", module="seasonal_brew", category="World Events/Brewfest", name="Strange Brew", description="Acquire the Brewfest beers listed below. Don't drink them all at once!", points="10", parent="World Events", type="36"}}
A{"Durotar", 1203, 0.4060, 0.1800, criterion=8886, side="horde", season="Brewfest", trivia={criteria="Long Stride Brew", module="seasonal_brew", category="World Events/Brewfest", name="Strange Brew", description="Acquire the Brewfest beers listed below. Don't drink them all at once!", points="10", parent="World Events", type="36"}}
A{"Durotar", 1203, 0.4080, 0.1700, criterion=8882, side="horde", season="Brewfest", trivia={criteria="Ogre Mead", module="seasonal_brew", category="World Events/Brewfest", name="Strange Brew", description="Acquire the Brewfest beers listed below. Don't drink them all at once!", points="10", parent="World Events", type="36"}}
A{"Durotar", 1203, 0.4060, 0.1800, criterion=8887, side="horde", season="Brewfest", trivia={criteria="Path of Brew", module="seasonal_brew", category="World Events/Brewfest", name="Strange Brew", description="Acquire the Brewfest beers listed below. Don't drink them all at once!", points="10", parent="World Events", type="36"}}
A{"Durotar", 1203, 0.4060, 0.1800, criterion=8891, side="horde", season="Brewfest", trivia={criteria="Small Step Brew", module="seasonal_brew", category="World Events/Brewfest", name="Strange Brew", description="Acquire the Brewfest beers listed below. Don't drink them all at once!", points="10", parent="World Events", type="36"}}
A{"Durotar", 1203, 0.4020, 0.1700, criterion=8890, side="horde", season="Brewfest", trivia={criteria="Stout Shrunken Head", module="seasonal_brew", category="World Events/Brewfest", name="Strange Brew", description="Acquire the Brewfest beers listed below. Don't drink them all at once!", points="10", parent="World Events", type="36"}}
A{"Durotar", 1203, 0.4080, 0.1700, criterion=9014, side="horde", season="Brewfest", trivia={criteria="Mudder's Milk", module="seasonal_brew", category="World Events/Brewfest", name="Strange Brew", description="Acquire the Brewfest beers listed below. Don't drink them all at once!", points="10", parent="World Events", type="36"}}

-- World Events/Brewfest: Brew of the Year
A{"Ironforge", 1183, 0.1870, 0.5210, criterion=3518, side="alliance", trivia={criteria="Metok's Bubble Bock", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Ironforge", 1183, 0.1870, 0.5210, criterion=3526, side="alliance", trivia={criteria="Aromatic Honey Brew", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Ironforge", 1183, 0.1870, 0.5210, criterion=3516, side="alliance", trivia={criteria="Stranglethorn Brew", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Ironforge", 1183, 0.1870, 0.5210, criterion=3517, side="alliance", trivia={criteria="Springtime Stout", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Ironforge", 1183, 0.1870, 0.5210, criterion=3520, side="alliance", trivia={criteria="Izzard's Ever Flavor", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Ironforge", 1183, 0.1870, 0.5210, criterion=3521, side="alliance", trivia={criteria="Draenic Pale Ale", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Ironforge", 1183, 0.1870, 0.5210, criterion=3522, side="alliance", trivia={criteria="Blackrock Lager", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Ironforge", 1183, 0.1870, 0.5210, criterion=3523, side="alliance", trivia={criteria="Binary Brew", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Ironforge", 1183, 0.1870, 0.5210, criterion=3525, side="alliance", trivia={criteria="Autumnal Acorn Ale", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Ironforge", 1183, 0.1870, 0.5210, criterion=3519, side="alliance", trivia={criteria="Lord of Frost's Private Label", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Ironforge", 1183, 0.1870, 0.5210, criterion=3524, side="alliance", trivia={criteria="Bartlett's Bitter Brew", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Ironforge", 1183, 0.1870, 0.5210, criterion=3515, side="alliance", trivia={criteria="Wild Winter Pilsner", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Orgrimmar", 1183, 0.5060, 0.7360, criterion=3518, side="horde", trivia={criteria="Metok's Bubble Bock", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Orgrimmar", 1183, 0.5060, 0.7360, criterion=3526, side="horde", trivia={criteria="Aromatic Honey Brew", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Orgrimmar", 1183, 0.5060, 0.7360, criterion=3516, side="horde", trivia={criteria="Stranglethorn Brew", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Orgrimmar", 1183, 0.5060, 0.7360, criterion=3517, side="horde", trivia={criteria="Springtime Stout", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Orgrimmar", 1183, 0.5060, 0.7360, criterion=3520, side="horde", trivia={criteria="Izzard's Ever Flavor", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Orgrimmar", 1183, 0.5060, 0.7360, criterion=3521, side="horde", trivia={criteria="Draenic Pale Ale", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Orgrimmar", 1183, 0.5060, 0.7360, criterion=3522, side="horde", trivia={criteria="Blackrock Lager", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Orgrimmar", 1183, 0.5060, 0.7360, criterion=3523, side="horde", trivia={criteria="Binary Brew", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Orgrimmar", 1183, 0.5060, 0.7360, criterion=3525, side="horde", trivia={criteria="Autumnal Acorn Ale", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Orgrimmar", 1183, 0.5060, 0.7360, criterion=3519, side="horde", trivia={criteria="Lord of Frost's Private Label", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Orgrimmar", 1183, 0.5060, 0.7360, criterion=3524, side="horde", trivia={criteria="Bartlett's Bitter Brew", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
A{"Orgrimmar", 1183, 0.5060, 0.7360, criterion=3515, side="horde", trivia={criteria="Wild Winter Pilsner", module="seasonal_brew", category="World Events/Brewfest", name="Brew of the Year", description="Sample 12 beers featured in the Brew of the Month club.", points="10", parent="World Events", type="28"}}
